### ISSUE TITLE
[Bug]:  JSON parse error

### ISSUE THREAD

**Issue by me-to-you93** [bropat/eufy-security-client#344]
### Client version

2.6.2

### Node version

16.20.1

### Operating System type

Docker

### Operating system version

Raspbian, Jeedom Docker Management

### Describe the bug

Hello,

I am trying to use the Jeedom Eufy plugin which uses the eufy-security-ws image.
When trying to start the daemon, I have a JSON Parsing error, exactly as stated in this [bug report on eufy-security-ws repo](https://github.com/bropat/eufy-security-ws/issues/230).
It seems the problem occurs in the eufy-security-client lib, I tried with both the primary account and an invited account, same result.
I don't know how to give you the corrupted JSON ?

Thank you for your job !

### To reproduce

Through Jeedom's Eufy plugin and eufy-security-ws image, while launching the daemon.
The Eufy connection is OK.

### Screenshots & Logfiles

2023-07-22 10:06:30.703  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-07-22 10:06:34.328  INFO  Connected to station XXXXXXXXXXXX on host 192.168.1.42 and port 29503 
2023-07-22 10:06:34.657  ERROR JSON parse error {"r 
 SyntaxError  Unexpected end of JSON input
error stack:
• utils.ts:151 parseJSON
    node_modules/eufy-security-client/src/utils.ts:151:21

• parameter.ts:45 readValue
    node_modules/eufy-security-client/src/http/parameter.ts:45:41

• device.ts:132 updateRawProperty
    node_modules/eufy-security-client/src/http/device.ts:132:45

• device.ts:64 <anonymous>
    node_modules/eufy-security-client/src/http/device.ts:64:22

• device.ts:63 update
    node_modules/eufy-security-client/src/http/device.ts:63:35

• device.ts:37 initializeState
    node_modules/eufy-security-client/src/http/device.ts:37:14

• device.ts:45 initialize
    node_modules/eufy-security-client/src/http/device.ts:45:14

• eufysecurity.ts:625 <anonymous>
    node_modules/eufy-security-client/src/eufysecurity.ts:625:32

**Comment by jrunning** [comment]
I'm having the same issue on Home Assistant 2023.7.3:

```
2023-07-23 17:58:39.807  ERROR JSON parse error {"r 
 SyntaxError  Unexpected end of JSON input
error stack:
• utils.ts:151 parseJSON
    usr/src/app/node_modules/eufy-security-client/src/utils.ts:151:21
• parameter.ts:45 readValue
    usr/src/app/node_modules/eufy-security-client/src/http/parameter.ts:45:41
• device.ts:132 updateRawProperty
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:132:45
• device.ts:64 <anonymous>
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:64:22
• device.ts:63 update
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:63:35
• device.ts:37 initializeState
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:37:14
• device.ts:45 initialize
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:45:14
• eufysecurity.ts:625 <anonymous>
    usr/src/app/node_modules/eufy-security-client/src/eufysecurity.ts:625:32
```

**Comment by PhilippEngler** [comment]
Are the devices we are talking here about the doorbell dual?
Same problem here with a T8213 (battery doorbell dual) with two properties (2707 and 2708). Before setting the corresponding value in the app I got this:

`{
	"param_id": 0,
	"device_sn": "T8213PXXXXXXXXXX",
	"param_type": 2707,
	"param_value": "{\"r",
	"create_time": 1690044248,
	"update_time": 1690044248,
	"status": 1
},`

after changing the value in the app I got this:

`{
	"param_id": 0,
	"device_sn": "T8213PXXXXXXXXXX",
	"param_type": 2707,
	"param_value": "{\"radar_wd_distance\":2}",
	"create_time": 1690044248,
	"update_time": 1690044248,
	"status": 1
},`

and the error is gone.

**Comment by me-to-you93** [comment]
For me the devices are 2x 2C Pro cam (T8142) on a homebase 2 (T8010).
I don't understand what do you mean by properties.
Can you tell me how to get the JSON response ?

**Comment by PhilippEngler** [comment]
@me-to-you93: Not sure how to enable debug logs with eufy-security-ws.
@bropat: Could you have a look [here](https://github.com/PhilippEngler/eufy-security-client/commit/002ae13077b27a508b77e835a7d08f2a1113415d), this does not solve the wrong JSON, but it delivers a error message with the incorrect property number.

**Comment by bropat** [comment]
@PhilippEngler 
Thank you very much. I have implemented your changes.
The fact is that from time to time incomplete values are delivered by the Eufy Cloud for some parameters... :(

**Comment by me-to-you93** [comment]
Hello,

Sorry but in my case, after update to eufy-client-ws 1.6.2 which uses eufy-security-client 2.7.1, I still have the same problem.
I guess my JSON parsing error was different from @PhilippEngler's one.
I don't see the JSON returned by eufy API, if you tell me how to provide it to you I would be happy to do so.

I believe you can reopen this issue.
Thank you

**Comment by PhilippEngler** [comment]
The solution @bropat has implemented did not and could not resolve the error, because it is delivered from the api itself. Maybe the 2c pro with the new model number is not compatible, but at the moment I don't think so. Please check first your log files.
With the new version, you should receive two log entries like:

```
JSON parse error {
 data: '{"r',
 error: SyntaxError: Unexpected end of JSON input
     at JSON.parse ()
     at parseJSON (/usr/local/addons/eufySecurity/eufySecurityApi/utils.js:147:21)
     at ParameterHelper.readValue (/usr/local/addons/eufySecurity/eufySecurityApi/http/parameter.js:50:63)
     ...`
     at Devices.updateDevice (/usr/local/addons/eufySecurity/eufySecurityApi/devices.js:221:44)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}
```

and

```
Non-parsable parameter value received from eufy cloud. Will be ignored. { type: XXXX, value: '{"r' }
```

**Comment by me-to-you93** [comment]
Yes you're right I have some more informations below : 
Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2707,
  value: '{"r'
}
 and also
{
  type: 2708,
  value: '{"r'
}

**Comment by kvanbiesen** [comment]
same here

```
2023-08-21 15:26:55.856  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2708,
  value: '{"r'
}
2023-08-21 15:35:56.843  ERROR JSON parse error 
{
  data: '{"r',
  error: SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at parseJSON (/usr/src/app/node_modules/eufy-security-client/build/utils.js:147:21)
      at Function.readValue (/usr/src/app/node_modules/eufy-security-client/build/http/parameter.js:50:63)
      at BatteryDoorbellCamera.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:127:57)
      at /usr/src/app/node_modules/eufy-security-client/build/http/device.js:54:22
      at Array.forEach (<anonymous>)
      at BatteryDoorbellCamera.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:53:35)
      at EufySecurity.updateDevice (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:344:44)
      at EufySecurity.handleDevices (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:560:22)
      at HTTPApi.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:167:50)
}
2023-08-21 15:35:56.844  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2707,
  value: '{"r'
}
2023-08-21 15:35:56.844  ERROR JSON parse error 
{
  data: '{"r',
  error: SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at parseJSON (/usr/src/app/node_modules/eufy-security-client/build/utils.js:147:21)
      at Function.readValue (/usr/src/app/node_modules/eufy-security-client/build/http/parameter.js:50:63)
      at BatteryDoorbellCamera.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:127:57)
      at /usr/src/app/node_modules/eufy-security-client/build/http/device.js:54:22
      at Array.forEach (<anonymous>)
      at BatteryDoorbellCamera.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:53:35)
      at EufySecurity.updateDevice (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:344:44)
      at EufySecurity.handleDevices (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:560:22)
      at HTTPApi.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:167:50)
}

```

Dont notice anything not working tho, just logspam
