### ISSUE TITLE
[Feature request]: Add support for Eufy video S3 max (T85V0) or Familylock

### ISSUE THREAD

**Issue by mohammad-shadmehr** [bropat/eufy-security-client#679]
### Describe the solution you'd like

I have multiple eufy devices alredy integrated into HA which includes this new Eufy Video S3 max. The device is showed up in HA but with no useful entities:

<img width="990" height="767" alt="Image" src="https://github.com/user-attachments/assets/61060d6d-2df4-4f14-995f-f22f5fab3ead" />

It seems the device is not supported by far with this integration and wonder if it can be added to the supported devices list

**Comment by max246** [comment]
Fixed 3.8.0

**Comment by mohammad-shadmehr** [comment]
I still cant see other entities for the device in HA.
Eufy security ver. 8.2.4
Eify security ws: 2.1.0

**Comment by DrSpaldo** [comment]
Yep, same for me. The device shows up but you can’t do anything with it, all the controls and info is missing… 

![Image](https://github.com/user-attachments/assets/5684bbaa-b585-4906-bcec-d6636adb6d29)

@max246 this issue isn’t completed 

Eufy security ver. 8.2.4
Eify security ws: 2.1.0
